version: '3.8'

services:
  web:
    build: .
    container_name: fleet_loginexia
    restart: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Madrid
    networks:
      - fleet_network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: fleet_redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fleet_network
    command: redis-server --appendonly yes

networks:
  fleet_network:
    driver: bridge

volumes:
  redis_data:
    driver: local

